name: Build and deploy WAR app to Azure Web App - hrs-webapp   #trigget test

on:
  push:
    branches:
      - master  # Change to 'master' if that's your default branch
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '8'
          distribution: 'temurin'  # Use 'temurin' for Java 8 support

      - name: Build with Maven
        run: mvn clean install

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: java-app
          path: target/*.war

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: java-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'hrs-webapp'  # Your Azure Web App name
          slot-name: 'Production'
          package: '*.war'
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
