name: Build and Initialize Web App

on:
  push:
    branches:
      - master

jobs:
  build-and-init:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Install MySQL client
        run: sudo apt-get update && sudo apt-get install -y mysql-client

      - name: Initialize MySQL Database
        env:
          DB_HOST: hrs-webapp-server.mysql.database.azure.com
          DB_USER: "pavekzchds"
          DB_PASSWORD: "i711i9$BTUsxZJv3"
          DB_NAME: hrs-webapp-database
        run: |
          mysql -h $DB_HOST -u $DB_USER -p"$DB_PASSWORD" $DB_NAME < sql/init.sql

      - name: Build WAR with Maven
        working-directory: home-renovation-solutions
        run: mvn clean package

      - name: Upload WAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: hrs-webapp
          path: home-renovation-solutions/target/*.war

  deploy:
    needs: build-and-init
    runs-on: ubuntu-latest

    steps:
      - name: Download WAR artifact
        uses: actions/download-artifact@v4
        with:
          name: hrs-webapp
          path: .

      - name: Locate and Rename WAR file to ROOT.war
        id: rename
        run: |
          echo "Renaming WAR file to ROOT.war for root context deployment..."
          WAR_PATH=$(find . -name "*.war" | head -n 1)
          cp "$WAR_PATH" ROOT.war
          echo "WAR_PATH=ROOT.war" >> $GITHUB_ENV

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: hrs-webapp
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          package: ${{ env.WAR_PATH }}
